---
- name: Get Volume Snapshots
  ansible.builtin.import_playbook: Get-Volume-Snapshots.yaml

- name: Get Volume Snapshot Details
  #
  # Required Parameter:
  #   SnapshotName or SnapshotId
  #   VolumeName
  #
  # ansible-playbook Get-Snapshot-Details.yaml -e "VolumeName=' ' SnapshotName=' '"
  hosts: localhost
  vars:
    method: "GET"
  tasks:
    - name: Check Snapshot Name and set URL
      vars: 
        key: "{{ SnapshotName }}"
      ansible.builtin.set_fact:
        request_uri: "{{ myvol.resourceUri }}/snapshots/{{ snapshots[key].id }}"
      when: SnapshotName is defined and SnapshotName != ""

    - name: Check Snapshot ID and set URL
      ansible.builtin.set_fact:
        request_uri: "{{ myvol.resourceUri }}/snapshots/{{ SnapshotId }}"
      when: SnapshotId is defined and SnapshotId != ""      

    - name: DSCC API Call
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Store the result
      ansible.builtin.copy:
        content: "{{ response | to_json }}"
        dest: "{{ response.json.name }}.json"
        mode: '0644'    

    - name: Show result.status
      vars:
        elementname: "Snapshot"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml

