---
- name: Get Volume Details
  # v1 09/28/2029 Thomas Beha
  #
  # Parameter:
  #   VolumeName
  #
  # ansible-playbook Get-Volume-Details.yaml -e "VolumeName='AnsibleTestVolume_01'"


  hosts: localhost
  vars:
    method: "GET"
    request_uri: "{{ myvol.resourceUri }}"
  tasks:
    - name: Read volume list
      ansible.builtin.set_fact:
        volumes: "{{ lookup( 'file', 'volumes.json' ) | from_json }}"

    - name: Get volume
      vars:
        key: "{{ VolumeName }}"
      ansible.builtin.set_fact:
        myvol: "{{ volumes[key] }}"

    - name: DSCC API Call
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Show results 
      vars:
        elementname: "{{VolumeName}}: "
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml    
