---
#- import_playbook: Get-Volumes.yaml 
- name: Get Create Snapshot
  # v1 10/07/2029 Thomas Beha
  #
  # Required Parameter:
  #   VolumeName
  #   
  # Optional Parameter:
  #   NamePattern - Name pattern: "PARENT_TIMESTAMP", "PARENT_SEC_SINCE_EPOCH", "CUSTOM"
  #   Comment - string or null 
  #   SnapshotName - Snapshot Name or null
  #   ExpireSecs - Expiration time ins seconds
  #   ReadOnly - Boolean
  #   RetainSecs / Retention time in seconds 
  #
  #   Attention if a CustomName is defined for the Snapshot then the NamePattern entry will be set to "CUSTOM". 
  #   
  # ansible-playbook Create-Snapshot.yaml -e "VolumeName='AnsibleTestVolume_01' ..."

  hosts: localhost
  vars:
    method: "POST"
    request_uri: "{{ myvol.resourceUri }}/snapshots"
    namePattern: "PARENT_TIMESTAMP"
    comment: "Created by Thomas B. with Ansible"
    readOnly: true
  tasks:

    - name: Check for Name Pattern
      ansible.builtin.set_fact:
        namePattern: "{{  NamePattern }}"
      when: NamePattern is defined and NamePattern != ""

    - name: Check for Comment
      ansible.builtin.set_fact:
        comment: "{{  Comment }}"
      when: Comment is defined and Comment != ""

    - name: Check for ReadOnly
      ansible.builtin.set_fact:
        readOnly: "{{ ReadOnly }}"
      when: ReadOnly is defined and ReadOnly != ""

    - name: Check For Snapshot Name
      ansible.builtin.set_fact:
          customName: "{{ SnapshotName }}"
          namePattern: "CUSTOM"
      when: SnapshotName is defined and SnapshotName != ""

    - name: Write Base Request Body 
      ansible.builtin.copy:
        dest: '../Outputs/variables.yaml'
        mode: '0644'
        content: |
              body:
                comment: "{{ comment }}"
                namePattern: "{{ namePattern }}"
                readOnly: {{ readOnly }}

    - name: Add Snapshot Name to Request Body
      ansible.builtin.lineinfile:
        path: '../Outputs/variables.yaml'
        line: "  customName: '{{ customName }}'"
        insertafter: EOF
      when: customName is defined
    
    - name: Check for Expiration
      ansible.builtin.lineinfile: 
        path: '../Outputs/variables.yaml'
        line: "  expireSecs: '{{ ExpireSecs }}'"
        insertafter: EOF
      when: ExpireSecs is defined and ExpireSecs != ""

    - name: Check for Retentiontime
      ansible.builtin.lineinfile: 
        path: '../Outputs/variables.yaml'
        line: "  retainSecs: '{{ RetainSecs }}'"
        insertafter: EOF
      when: RetainSecs is defined and RetainSecs != "" 

    - name: Read volume list
      ansible.builtin.set_fact:
        volumes: "{{ lookup( 'file', '../Outputs/volumes.json' ) | from_json }}"

    - name: Get volume id
      vars:
        key: "{{ VolumeName }}"
      ansible.builtin.set_fact:
        myvol: "{{ volumes[key] }}"

    - name: Read the Rest API Body to get the correct variable types 
      ansible.builtin.include_vars:
        file: '../Outputs/variables.yaml'

    - name: DSCC API Call GET storage systems
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Display Command Reponse
      vars:
        elementname: "Snapshot"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml 
