---
- name: Create Volumes
  # v2 07/15/2026 Thomas Beha
  #
  # Required Parameter:
  #   SystemName  name of the storage system
  #   VolumeName  name of the volume
  # Optional Parameter
  #   Size        Size (in MiB) of the volume to be created. Default value: 16384 (16GiB)
  #   CPG         User CPG. Default: SSD_r6
  #   Comment     
  #   Count                 volumes count, default: 1
  #   DataReduction         default: true
  #   Ransomware            default: true
  #   UserAllocWarning      default 1
  #   SnapshotAllocWarning  default: 1
  #
  # ansible-playbook Create-Volume.yaml -e "SystemName='CTC-MP-Block8' VolumeName='AnsibleTestVolume_01' CPG='SSD_r6' Size='20480' Comment='Ansible Test Thomas Beha' Count='1' DataReduction='true'"
  hosts: localhost
  vars:
    method: "POST"
    request_uri: "{{ storage['resourceUri'] }}/volumes"
    name: "{{ VolumeName }}"
    comment: "Thomas Beha - Ansible"
    userCpg: "SSD_r6"
    count: 1
    dataReduction: true
    ransomWare: true
    size: 10240
    userAllocWarning: 5 
    snapshotAllocWarning: 5
  tasks:

    - name: Retrieve storage systems list
      ansible.builtin.set_fact:
        systems: "{{ lookup( 'file', '../Outputs/systems.json') | from_json }}"

    - name: Lookup system
      vars:
        key: "{{ SystemName }}"
      ansible.builtin.set_fact:
        storage: "{{ systems[key] }}"

    - name: Check Volume Size
      ansible.builtin.set_fact:
        size: "{{ Size }}" 
      when: Size is defined and Size != ""

    - name: Check Count
      ansible.builtin.set_fact:
        count: "{{  Count }}"
      when: Count is defined and Count != ""

    - name: Check DataReduction
      ansible.builtin.set_fact:
        dataReduction: "{{  DataReduction }}"
      when: DataReduction is defined and DataReduction != ""

    - name: Check Ransomware
      ansible.builtin.set_fact:
        ransomWare: "{{  RansomWare }}"
      when: RansomWare is defined and RansomWare != ""

    - name: Check snapshotAllocWarning
      ansible.builtin.set_fact:
        snapshotAlloc: "{{ SnapShotAllocWarning }}"
      when: SnapshotAllocWarning is defined and SnapshotAllocWarning != ""

    - name: Check userAllocWarning
      ansible.builtin.set_fact:
        userAllocWarning: "{{ SnapShotAllocWarning }}"
      when: UserAllocWarning is defined and UserAllocWarning != ""

    - name: Write Request Body
      ansible.builtin.copy:
        dest: '../Outputs/variables.yaml'
        mode: '0644'
        content: |
              body:
                name: "{{ VolumeName }}"
                comments: "{{ comment }}"
                userCpg: "{{ userCpg }}"
                count: {{count}}
                dataReduction: {{ dataReduction }}
                ransomware: {{ ransomWare }}
                sizeMib: {{ size }}
                userAllocWarning: {{ userAllocWarning }}
                snapshotAllocWarning: {{ snapshotAllocWarning }}

    - name: Read the Rest API Body
      ansible.builtin.include_vars:
        file: '../Outputs/variables.yaml'

    - name: DSCC API Call Create Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Show results 
      vars:
        elementname: "Volume"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml 
