---
- name: Create HostGroup
  # v1 10/10/2029 Thomas Beha
  #
  # Required Parameter:
  #   hostgroupName
  # Optional:
  #   Force
  #
  # ansible-playbook Create-HostGRoup -e "hostgroupName=' ' Force='true'"

  hosts: localhost
  vars:
    method: "DELETE"
    request_uri: "/api/v1/host-initiator-groups/{{ hostgroupid }}"
    force: true
  tasks:

    - name: Check Force Flag
      ansible.builtin.set_fact:
        force: "{{ Force }}"
      when: Force is defined and Force != ""
    
    - name: Get Access Token
      ansible.builtin.set_fact:
        token: "{{ lookup('file', 'token.txt') }}"

    - name: Read host_groups.json
      ansible.builtin.set_fact:
        host_groups: "{{ lookup('file', 'host_groups.json') }}"

    - name: Get hostgroup id
      vars:
        key: "{{ hostgroupName }}"
      ansible.builtin.set_fact:
        hostgroupid: "{{ host_groups[key] }}"

    - name: Delete HostGroup"
    - name: DSCC API Call
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Show results 
      vars:
        elementname: "HostGroup"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml 
