---
# v2 07/15/2026 Thomas Beha
  #
  # Displays the playbook results.
  # this playbook is actually imported in other playbooks 
  #   

- name: Show Body
  ansible.builtin.debug:
    msg: "{{ body }}"
  when: body is defined

- name: Write response
  ansible.builtin.debug: 
    var: result
  when: result is defined and elements is not defined 

- name: Display short result
  ansible.builtin.debug:
    var: elements
  when: elements is defined

- name: Write Elements
  ansible.builtin.debug:
    msg: "Number of {{ elementname }}: {{ result.json['total'] }}  pageLimit: {{ result.json['pageLimit'] }}"
  when: result.json['total'] is defined and result.json['pageLimit'] is defined

 