---
- name: Get Storage Systems Capacity
# Playbook get the list of storage systems registered in the DSCC
# (c) Thomas Beha, v3.0 08/28/2026
#
# Parameter:
#  SystemName
#
# Run Command: ansible-playbook Get-System-Capacity.yaml -e "SystemNane=' '"
#
  hosts: localhost
  vars:
    method: "GET"
    request_uri: "/api/v1/storage-systems?filter=name%20eq%20'{{SystemName}}'"
  tasks:

    - name: DSCC API Call - Get System
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get System
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Set new Request Uri - <storage systems resourceUri>/capacity-summary
      ansible.builtin.set_fact:
        request_uri: "{{ result.json['items'][0].resourceUri }}/capacity-summary"  

    - name: DSCC API Call
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Show Results 
      vars:
        elementname: "{{ SystemName }}-Capacity"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml

    - name: Store the System Capacity Details
      ansible.builtin.copy:
        content: "{{ response | to_json }}"
        dest: "{{ lookup('env','HOME') }}/.ansible/{{ SystemName }}.capacity.json"
        mode: '0644'
