---
- name: Get All VolumeSets
  # Playbook: Get all volumes
  # v1 09/26/2029 Thomas Beha
  # Retrieves of DSCC managed volumes
  #
  # Parameter: none
  #   limit:imit -
  #   offset -
  # Ouput: stored in "volumesets.json"
  # Output format:
  #   {
  #     <volume.name>: {
  #        id: volume.id,
  #        resourceUri: volume.resourceUri
  #      },
  #      ...
  #      <volume.name>: {
  #        ...
  #      }
  #   }
  #
  # Run Command:
  #   ansible-playbook Get-VolumeSets.yaml -e "offset='0' limit='250'"

  hosts: localhost
  vars:
    offset: "0"
    limit: "250"
    method: "GET"
    request_uri: "/api/v1/volume-sets?limit={{ limit }}&offset={{ offset }}"
  tasks:

    - name: Check for Offset
      ansible.builtin.set_fact:
        offset: "{{  Offset }}"
      when: Offset is defined and Offset != ""

    - name: Check for Limit
      ansible.builtin.set_fact:
        limit: "{{  Limit }}"
      when: Limit is defined and Limit != ""

    - name: DSCC API Call GET Data
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Initialize volume dictionary
      ansible.builtin.set_fact:
        volumesets: "{{ volumesets | default({}) }}"

    - name: Loop through Volumesets
      ansible.builtin.set_fact:
        volumesets: "{{ volumesets | combine({item.name: {'id': item.id, 'resourceUri': item.resourceUri, 'systemId':item.systemId}}) }}"
      with_items: "{{ response.json['items'] }}"

    - name: Store the volumesets List
      ansible.builtin.copy:
        content: "{{ volumesets | to_json }}"
        dest: "../Outputs/volumesets.json"
        mode: '0644'

    - name: Show results 
      vars:
        elements: "{{ volumesets }}"
        elementname: "Volumes"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml    
