---
- name: Get Volume Snapshots
  # v1 10/07/2029 Thomas Beha
  #
  # Parameter:
  #   VolumeName
  #
  # ansible-playbook Get-Volume-Details.yaml -e "VolumeName='AnsibleTestVolume_01'"
  hosts: localhost
  vars:
    method: "GET"
    request_uri: "{{ myvol.resourceUri }}/snapshots"
  tasks:
    - name: Read volume list
      ansible.builtin.set_fact:
        volumes: "{{ lookup( 'file', '../Outputs/volumes.json') | from_json }}"

    - name: Get volume
      vars:
        key: "{{ VolumeName }}"
      ansible.builtin.set_fact:
        myvol: "{{ volumes[key] }}"

    - name: DSCC API Call
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Initialize Snapshot dictionary
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | default({}) }}"

    - name: Loop through Systems
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | combine({item.name: {
          'id': item.id,
          'systemId': item.systemId
          } })
        }}"
      with_items: "{{ response.json['items'] }}"

    - name: Show results
      vars:
        elements: "{{ snapshots }}"
        elementname: "{{ VolumeName}} - Snapshots "
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml
