---
- name: Get Tasks List
  # (c) Thomas Beha, v2.0 10/13/2024
  # Retrieves the list of the host groups in the DSCC and stores it in host_groups.json
  #
  # Parameter:
  #   
  # Output: stored in tasks/taskid.json
  # Output format:
  #   {
  #     <hostgroup.name>: <hostgroup.id>,
  #     ...
  #   }
  #
  # Run command: ansible-playbook Get-Tasks.yaml
  hosts: localhost
  vars:
    offset: 0
    limit: 50
    method: "GET"    
    request_uri: "/api/v1/tasks?offset={{ offset }}&limit={{ limit }}"
  tasks:
    - name: Check for offset 
      ansible.builtin.set_fact:
        offset: "{{ Offset }}"
      when: Offset is defined and Offset != "" 

    - name: Check for limit 
      ansible.builtin.set_fact:
        limit: "{{ Limit }}"
      when: Limit is defined and Limit != "" 

    - name: DSCC API Call GET tasks
      vars:
      ansible.builtin.include:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Store the data in a file
      ansible.builtin.copy:
        content: "{{ response.json | to_json }}"
        dest: "../Output/tasks.json"
        mode: '0644'

    - name: Show results 
      vars:
        elementname: "Tasks"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml    