---
- name: Get Volume Details
  # v2 11/20/2024 Thomas Beha
  #
  # Parameter:
  #   VolumeName
  #
  # ansible-playbook Get-Volume-Details.yaml -e "VolumeName='AnsibleTestVolume_01'"


  hosts: localhost
  vars:
    method: "GET"
    request_uri: "/api/v1/volumes?filter=name%20eq%20'{{VolumeName}}'"
  tasks:
    - name: DSCC API Call - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Set resourceURI      
      ansible.builtin.set_fact:
        request_uri: "{{ result.json['items'][0].resourceUri }}"

    - name: DSCC API Call - Get Volume Details
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Store the data in a file
      ansible.builtin.copy:
        content: "{{ response.json | to_json }}"
        dest: "../Outputs/{{ VolumeName }}.json"
        mode: '0644'


    - name: Show results 
      vars:
        elementname: "{{VolumeName}}: "
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml   
