---
- name: Get Volume Snapshots
  # v1 10/07/2029 Thomas Beha
  #
  # Parameter:
  #   VolumeName
  #
  # ansible-playbook Get-Volume-Details.yaml -e "VolumeName='AnsibleTestVolume_01'"
  hosts: localhost
  vars:
    method: "GET"
    request_uri: "/api/v1/volumes?filter=name%20eq%20'{{VolumeName}}'"
  tasks:
    - name: DSCC API Call - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Set resourceURI      
      ansible.builtin.set_fact:
        request_uri: "{{ result.json['items'][0].resourceUri }}/snapshots"

    - name: DSCC API Call Get Volume Snapshots
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Initialize Snapshot dictionary
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | default({}) }}"

    - name: Loop through Snaspshots
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | combine({item.name: {'id': item.id, 'systemId':item.systemId}}) }}"
      with_items: "{{ response.json['items'] }}"

    - name: Show results
      vars:
        elements: "{{ snapshots }}"
        elementname: "{{ VolumeName}} - Snapshots "
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml
