- name: Set URI
  ansible.builtin.set_fact:
    request_uri: "/api/v1/host-initiator-groups"
- name: Get HostGroups
  ansible.builtin.include_tasks:
    file: DSCC-API-Call.yaml 
- name: Increase Limits if needed
  ansible.builtin.set_fact:
    request_uri: "/api/v1/host-initiators?limit={{ response.json.total }}&offset=0"
  when: 
    - response.json is defined 
    - response.json.total > response.json.pageLimit  
- name:  Get All Hosts
  ansible.builtin.include_tasks:
    file: DSCC-API-Call.yaml
  when: 
    - response.json is defined  
    - response.json.total > response.json.pageLimit