- name: Set URI
  ansible.builtin.set_fact:
    request_uri: "{{assocLink.value}}"
- name: DSCC API GET {{request_uri}}
  vars: 
    method: "GET"
  ansible.builtin.include_tasks:
    file: DSCC-API-Call.yaml
  ignore_errors: yes
- name: Save Result
  ansible.builtin.copy:
    content: "{{response.json | to_nice_json}}"
    dest: "../Outputs/{{SystemName}}.{{assocLink.key}}.json"
    mode: '0644'  
  when: response.json is defined
- name: Check Response
  ansible.builtin.debug:
    msg: "WARNING: No Response on {{request_uri}}"
  when: response == ""
