---
#- import_playbook: Get-Volumes.yaml 
#- import_playbook: Get-HostGroups.yaml
- name: Promote Snapshot playbook
# Export Volume playbook
# v1.0 9/27/2024 Thomas Beha
#
# Parameters:
#   VolumeName - name of volume
#   SnapshotName - name of the snapshot that should be promoted
#
# Run command:
#   ansible-playbook Export-Volume.yaml -e "VolumeName='<volumeName>' HostGroupName='<hostgroupName>"
#
  hosts: localhost
  vars:
    method: "GET"
    request_uri: "/api/v1/volumes?filter=name%20eq%20'{{VolumeName}}'"
  tasks:

    - name: DSCC API Call - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == '401'

    - name: Set to snapshot resourceURI      
      ansible.builtin.set_fact:
        request_uri: "{{ result.json['items'][0].resourceUri }}/snapshots"

    - name: DSCC API Call Get Volume Snapshots
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Initialize Snapshot dictionary
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | default({}) }}"

    - name: Loop through Snaspshots
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | combine({item.name: {'id': item.id, 'systemId':item.systemId}}) }}"
      with_items: "{{ response.json['items'] }}"

    - name: Check Snapshot Name and set URL
      vars:
        key: "{{ SnapshotName }}"
      ansible.builtin.set_fact:
        snapshot: "{{ snapshots[key] }}"
      when: SnapshotName is defined and SnapshotName != ""

    - name: Set resourceURI      
      ansible.builtin.set_fact:
        request_uri: "{{ systemuri}}/snapshots/{{ snapshot.id }}"
        method: "POST"

    - name: DSCC API Call - Promote Snapshot 
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Show results 
      vars:
        elementname: "Promote Snapshot"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml 