---
- name: Show Data
  # v1 09/26/2029 Thomas Beha
  # Displays the dictionary stored in the file {{filename}}
  #
  # ansible-playbook Show-Data.yaml --extra-vars "filename='<filename>'' searchKey='...'"

  hosts: localhost #suo04tlb002
  vars:

  tasks:

    - name: Read the dictionary from file 
      ansible.builtin.set_fact:
        data: "{{ lookup('file', '../Outputs/{{ filename }}')}}"

    - name: Display searchKey
      ansible.builtin.debug:
        var: searchKey
   
    - name: Display Data
      vars:
        key: "{{ searchKey }}"
      ansible.builtin.debug:
        var: data[key]
