---
- name: Test
  # v1 09/27/2029 Thomas Beha
  #
  # Required Parameter:
  #   SystemName  name of the storage system
  #   VolumeName  name of the volume
  # Optional Parameter
  #   Size        Size (in MiB) of the volume to be created. Default value: 16384 (16GiB)
  #   CPG         User CPG. Default: SSD_r6
  #   Comment     
  #   Count                 volumes count, default: 1
  #   DataReduction         default: true
  #   UserAllocWarning      default 5
  #   SnapshotAllocWarning  default: 5
  #
  # ansible-playbook Create-Volume.yaml -e "SystemName='CTC-MP-Block8' VolumeName='AnsibleTestVolume_01' CPG='SSD_r6' Size='20480' Comment='Ansible Test Thomas Beha' Count='1' DataReduction='true'"

  hosts: localhost

  vars_files: credentials.yml

  tasks:

  - name: Read HostGroups
    ansible.builtin.set_fact: 
      host_groups: "{{ lookup('file', '../Outputs/host_groups.json') | from_json }}"

  - name: Get hostgroup
    vars:
      key: "{{ HostGroupName }}"
    ansible.builtin.debug:
      msg: "{{ key }}  :: {{ host_groups[key]['id']}}"

    