---
- name: Test
  # v1 09/27/2029 Thomas Beha
  #
  # Required Parameter:
  #   SystemName  name of the storage system
  #   VolumeName  name of the volume
  # Optional Parameter
  #   Size        Size (in MiB) of the volume to be created. Default value: 16384 (16GiB)
  #   CPG         User CPG. Default: SSD_r6
  #   Comment     
  #   Count                 volumes count, default: 1
  #   DataReduction         default: true
  #   UserAllocWarning      default 5
  #   SnapshotAllocWarning  default: 5
  #
  # ansible-playbook Create-Volume.yaml -e "SystemName='CTC-MP-Block8' VolumeName='AnsibleTestVolume_01' CPG='SSD_r6' Size='20480' Comment='Ansible Test Thomas Beha' Count='1' DataReduction='true'"

  hosts: localhost
  vars:
    
  tasks:

    - name: Read volume list
      ansible.builtin.set_fact:
        volumes: "{{ lookup( 'file', '../Outputs/volumes.json') | from_json }}"

    - name: Get volume
      vars:
        key: "{{ VolumeName }}"
      ansible.builtin.set_fact:
        myvol: "{{ volumes[key] }}"

    - name: Set API Call Parameter
      ansible.builtin.set_fact:
        method: "GET"
        request_uri: "{{ myvol.resourceUri }}/snapshots"

    - name: DSCC API Call
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Initialize Snapshot dictionary
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | default({}) }}"

    - name: Loop through Response
      ansible.builtin.set_fact:
        snapshots: "{{ snapshots | combine({item.name: item.id}) }}"
      with_items: "{{ response.json['items'] }}"

    - name: Display result
      ansible.builtin.debug:
        msg: "{{snapshots}}  "