---
- name: Test Call
  hosts: localhost
  vars:
    method: "GET"
  tasks:
  - name: Get Hosts
    ansible.builtin.include_tasks:
      file: GetAllHosts.yaml
  - name: Store the Hosts
    ansible.builtin.copy:
      content: "{{ response.json | to_nice_json }}"
      dest: "../Outputs/hosts.json"
      mode: '0644'
    when: response.json is defined  