---
- name: Test
  # v1 09/27/2029 Thomas Beha
  #
  # Required Parameter:
  #   SystemName  name of the storage system
  #   VolumeName  name of the volume
  # Optional Parameter
  #   Size        Size (in MiB) of the volume to be created. Default value: 16384 (16GiB)
  #   CPG         User CPG. Default: SSD_r6
  #   Comment     
  #   Count                 volumes count, default: 1
  #   DataReduction         default: true
  #   UserAllocWarning      default 5
  #   SnapshotAllocWarning  default: 5
  #
  # ansible-playbook Create-Volume.yaml -e "SystemName='CTC-MP-Block8' VolumeName='AnsibleTestVolume_01' CPG='SSD_r6' Size='20480' Comment='Ansible Test Thomas Beha' Count='1' DataReduction='true'"

  hosts: localhost
  vars:
    method: "GET"
    request_uri: "/api/v1/volumes?filter=name%20eq%20'{{VolumeName}}'"
  tasks:

    # First get Volume Uri
    - name: DSCC API Call - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Set Volume Resoure Uri
      ansible.builtin.set_fact:
        vol_uri: "{{ result.json['items'][0].resourceUri }}"
    
    # 2. Get HostGroup
    - name: Set HostGroup request_uri
      ansible.builtin.set_fact:
        request_uri: "/api/v1/host-initiator-groups?filter=name%20eq%20'{{HostGroupName}}'"
    
    - name: DSCC API Call - Get HostGroup
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get Host Group
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Set HostGroup
      ansible.builtin.set_fact:
        hostgroup: "{{ result.json['items'][0].id }}"

    # 3. Get snapshot Uri & Export the snapshot
    - name: Set resourceURI      
      ansible.builtin.set_fact:
        request_uri: "{{ vol_uri }}/snapshots?filter=name%20eq%20'{{SnapshotName}}'"

    - name: DSCC API Call - Get Snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get Snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Get System Uri
      ansible.builtin.set_fact:
        sys_uri: "{{ vol_uri | regex_replace('^(.*?)/volumes/.*', '\\1') }}"

    - name: Debug - voluri
      ansible.builtin.debug:
        msg: "{{ vol_uri }}"

    - name: Debug - sys_uri
      ansible.builtin.debug:
        msg: "{{ sys_uri }}"

    - name: Set Snapshot Id
      ansible.builtin.set_fact:
        request_uri: "{{ sys_uri }}/snapshots/{{ result.json['items'][0].id }}/un-export"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ request_uri  }}"

    - name: Set method
      ansible.builtin.set_fact:
        method: POST  

    - name: Set body
      ansible.builtin.set_fact:
        body:
          hostGroupIds: ["{{ hostgroup }}"]

    - name: DSCC API Call - export snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - export Snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Show results 
      vars:
        elementname: "Volume"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml 
