---
- name: Volume-Snapshot-UnExport
  # v2 08/31/2026 Thomas Beha
  #
  # Required Parameter:
  #   VolumeName - name of the snapshot base volume
  #   HostGroupName - name of the hostgroup the snapshot should be exported to
  #   SnapshotName  - name of the snapshot that should be exported
  # Optional Parameter:
  #
  # ansible-playbook UnExport-Volume-Snapshot.yaml -e "workspace=<workspaceid> VolumeName=' ' HostGroupName=' ' SnapshotName=' '"
  hosts: localhost

- name: UnExport Snapshots
  hosts: localhost
  vars:
    method: "GET"
    request_uri: "/api/v1/volumes?filter=name%20eq%20'{{VolumeName}}'"
  tasks:
     # First get Volume Uri
    - name: DSCC API Call - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get Volume
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Set Volume Resoure Uri
      ansible.builtin.set_fact:
        vol_uri: "{{ result.json['items'][0].resourceUri }}"
    
    # 2. Get HostGroup
    - name: Set HostGroup request_uri
      ansible.builtin.set_fact:
        request_uri: "/api/v1/host-initiator-groups?filter=name%20eq%20'{{HostGroupName}}'"
    
    - name: DSCC API Call - Get HostGroup
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get Host Group
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Set HostGroup
      ansible.builtin.set_fact:
        hostgroup: "{{ result.json['items'][0].id }}"

    # 3. Get snapshot Uri & Export the snapshot
    - name: Set resourceURI      
      ansible.builtin.set_fact:
        request_uri: "{{ vol_uri }}/snapshots?filter=name%20eq%20'{{SnapshotName}}'"

    - name: DSCC API Call - Get Snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - Get Snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Get System Uri
      ansible.builtin.set_fact:
        sys_uri: "{{ vol_uri | regex_replace('^(.*?)/volumes/.*', '\\1') }}"

    - name: Debug - voluri
      ansible.builtin.debug:
        msg: "{{ vol_uri }}"

    - name: Debug - sys_uri
      ansible.builtin.debug:
        msg: "{{ sys_uri }}"

    - name: Set Snapshot Id
      ansible.builtin.set_fact:
        request_uri: "{{ sys_uri }}/snapshots/{{ result.json['items'][0].id }}/export"

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ request_uri  }}"

    - name: Set method
      ansible.builtin.set_fact:
        method: POST  

    - name: Set body
      ansible.builtin.set_fact:
        body:
          hostGroupIds: ["{{ hostgroup }}"]

    - name: DSCC API Call - unexport snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-Call.yaml

    - name: Retry the command if status 401 - unexport Snapshot
      ansible.builtin.include_tasks:
        file: DSCC-API-401.yaml
      when: status == 401

    - name: Show results 
      vars:
        elementname: "UnExport Snapshot"
        result: "{{ response }}"
      ansible.builtin.include_tasks:
        file: DisplayResults.yaml  

 